apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData: #stringdata olarak yazarsaniz bu bilgileri ekranda oldugu gibi yazarsiniz data olarak yazarsaniz bunlarin data64 encoded halini yazmaniz gerekir
  db_server: db.example.com
  db_username: admin
  db_password: P@ssw0rd!